analysis:
  openai:
    models:
      analysis:
        default: gpt-4-turbo-preview
        settings:
          temperature: 0.1
      embedding:
        default: text-embedding-ada-002

fastapi:
  server_host: "0.0.0.0"
  server_port: 8000
  log_level: "info"

service:
  chroma:
    host: "10.0.1.10"
    port: 8001
    chroma_api_impl: "rest"
    settings:
      anonymized_telemetry: false
      allow_reset: true
  openai:
    chat:
      model: gpt-4-turbo-preview
      temperature: 0.1

data_sources:
  pubmed:
    base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils
    settings:
      api_key: ""  # Optional
      max_retries: 3
      retry_delay: 1.0
      timeout: 30.0

pubmed_settings:
  base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
  api_key: ""  # Optional
  max_retries: 3
  retry_delay: 1.0
  timeout: 30.0
